openapi: 3.0.1
info:
  title: FileConnector
  description: API Definition of FileConnector
  version: 1.0.0
servers:
- url: http://localhost:8290/fileconnector
paths:
  /:
    post:
      responses:
        default:
          description: Default response
